version: '3'

services:
  telegram-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - telegram-sessions:/app/sessions
    env_file:
      - .env

volumes:
  telegram-sessions: