version: '3'

services:
  telegram-api:
    build: .
    restart: always
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./:/app
      - telegram-sessions:/app/sessions
    env_file:
      - .env
    environment:
      - N8N_WEBHOOK_URL=http://localhost:5678/webhook/telegram

volumes:
  telegram-sessions: